config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from django.contrib.auth import views as auth_views

admin.site.site_header = "EASY Doctor Admin"
admin.site.site_title = "EASY Doctor Admin Portal"
admin.site.index_title = "Welcome to EASY Doctor Researcher Portal"

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('home/', include('home.urls', namespace='home')),
                  path('visit/', include('visit.urls', namespace='visit')),
                  path('patient/', include('patient.urls', namespace='patient')),
                  path('patient_visit/', include('patient_visit.urls', namespace='patient_visit')),
                  path("__debug__/", include("debug_toolbar.urls")),
                  # path('login/', auth_views.LoginView.as_view(), name='login'),
                  # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
                  path("accounts/", include("django.contrib.auth.urls")),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),

]

patient/urls.py
from django.urls import path

from . import views

app_name = 'patient'
urlpatterns = [
    path('', views.PatientListView.as_view(), name='patient_list'),
    path('<int:pk>/', views.PatientDetailView.as_view(), name='patient_detail'),
    path('patient_create/', views.PatientCreateView.as_view(), name='patient_create'),
    path('<int:pk>/patient_update/', views.PatientUpdateView.as_view(), name='patient_update'),
    path('<int:pk>/patient_delete/', views.PatientDeleteView.as_view(), name='patient_delete'),

]

patient_visit/urls.py
from django.urls import path

from . import views

app_name = 'patient_visit'
urlpatterns = [
    path('', views.PatientVisitListView.as_view(), name='patientvisit_list'),
    path('<int:pk>/', views.PatientVisitDetailView.as_view(), name='patientvisit_detail'),
    path('<int:pk>/update/', views.PatientVisitUpdateView.as_view(), name='patientvisit_update'),
    path('<int:pk>/delete/', views.PatientVisitDeleteView.as_view(), name='patientvisit_delete'),
    path('<int:pk>/pdf/', views.export_visit_to_pdf, name='patientvisit_pdf'),
]

visit/urls.py
from django.urls import path

from . import views

app_name = 'visit'
urlpatterns = [
    path('', views.DiagnosisListView.as_view(), name='diagnosis_list'),
    path('<slug:slug>/', views.DiagnosisDetailView.as_view(), name='diagnosis_detail'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    {% block link %}
    {% endblock link %}
    <script src="{% static 'scripts/bootstrap.min.js' %}"></script>


    {% block script %}
    {% endblock script %}

</head>
<body>


<div class="container-fluid">

    <div class="row">

        <div class="col-md-6 ">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <div class="col-md-1 "></div>

                    <a class="navbar-brand-t " href="{% url 'home:home' %}"> EASY Doctor - wersja testowa 0.1</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarText">
                      {% include 'navbar.html' %}
                    </div>
            </nav>

            {% block content %}
            {% endblock content %}

        </div>
        <div class="col-md-6">

            {% block sidebar %}
            {% endblock sidebar %}

        </div>
    </div>


</div>

{% block scriptend %}

{% endblock scriptend %}

<script src="{% static 'scripts/index.js' %}"></script>
</body>
</html>

templates/base_home.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% block link %}
    {% endblock link %}
    <script src="{% static 'scripts/bootstrap.min.js' %}"></script>
    {% block script %}
    {% endblock script %}

</head>

<body>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 ">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <div class="col-md-1 "></div>
                    <a class="navbar-brand-t " href="{% url 'home:home' %}"> EASY Doctor - wersja testowa 0.1</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"</span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarText">
                        {% block navbar %}
                        {% endblock navbar %}
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <br><br>
                {% block content %}
                {% endblock content %}
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>
</div>

{% block scriptend %}

{% endblock scriptend %}
<script src="{% static 'scripts/index.js' %}"></script>
</body>
</html>

templates/navbar.html
{% if user.is_authenticated %}

<ul class="navbar-nav me-auto mb-2 mb-lg-0">

    <li class="nav-item">
        <a class="nav-link" href="{% url 'visit:diagnosis_list' %}">Rozpoznania</a>
    </li>
    <li class="nav-item">

    </li>
    <li class="nav-item">

        <a class="nav-link" href="{% url 'patient:patient_list' %}">Pacjenci</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'patient:patient_create' %}">
            <button type="button" class="btn btn-outline-lightturquoise btn-sm">+</button>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'patient_visit:patientvisit_list' %}"> Wizyty</a>
    </li>

    <li class="nav-item ">
        <a class="nav-link" href="{% url 'logout' %}">
            <button type="button" class="btn btn-outline-lightpink btn-sm">Wyloguj</button>
        </a>
    </li>
</ul>
<span class="navbar-text">{{user.username}}</span>

{% else %}
<a href="{% url 'login' %}">
    <button type="button" class="btn btn-outline-lightturquoise ">
        Zaloguj
    </button>
</a>


{% endif %}