config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from django.contrib.auth import views as auth_views

admin.site.site_header = "EASY Doctor Admin"
admin.site.site_title = "EASY Doctor Admin Portal"
admin.site.index_title = "Welcome to EASY Doctor Researcher Portal"

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('home/', include('home.urls', namespace='home')),
                  path('visit/', include('visit.urls', namespace='visit')),
                  path('patient/', include('patient.urls', namespace='patient')),
                  path('patient_visit/', include('patient_visit.urls', namespace='patient_visit')),
                  path("__debug__/", include("debug_toolbar.urls")),
                  # path('login/', auth_views.LoginView.as_view(), name='login'),
                  # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
                  path("accounts/", include("django.contrib.auth.urls")),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),

]

patient/urls.py
from django.urls import path

from . import views

app_name = 'patient'
urlpatterns = [
    path('', views.PatientListView.as_view(), name='patient_list'),
    path('<int:pk>/', views.PatientDetailView.as_view(), name='patient_detail'),
    path('patient_create/', views.PatientCreateView.as_view(), name='patient_create'),
    path('<int:pk>/patient_update/', views.PatientUpdateView.as_view(), name='patient_update'),
    path('<int:pk>/patient_delete/', views.PatientDeleteView.as_view(), name='patient_delete'),

]

patient/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.core.mail import send_mail

from visit.models import TimeStampedModel

user = get_user_model()


class Patient(TimeStampedModel):
    first_name = models.CharField(max_length=150, verbose_name='imię', help_text='imię')
    last_name = models.CharField(max_length=150, verbose_name='nazwisko', help_text='nazwisko')
    email = models.EmailField(verbose_name='email', help_text='email')
    birth_date = models.DateField(verbose_name='Data urodzenia', help_text='Data urodzenia')
    address = models.CharField(max_length=250, verbose_name='adres', help_text='adres')
    pesel = models.CharField(max_length=20, verbose_name='PESEL', help_text='PESEL')
    phone = models.CharField(max_length=15, verbose_name='Tel.', help_text='Tel.', null=True, blank=True)
    doctor = models.ForeignKey(user, on_delete=models.CASCADE, related_name='patients', verbose_name='lekarz',
                               help_text='lekarz', default=2)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    # def email_user(self, subject, message, from_email=None, **kwargs):
    #     """Send an email to this user."""
    #     send_mail(subject, message, from_email, [self.email], **kwargs)

    class Meta:
        verbose_name = 'pacjent'
        verbose_name_plural = 'pacjenci'

    def __str__(self):
        return self.get_full_name()

    def get_absolute_url(self):
        return reverse('patient:patient_detail', kwargs={'pk': self.pk})

patient/forms.py
from django import forms

from .models import Patient


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('first_name', 'last_name', 'birth_date', 'pesel', 'email', 'birth_date', 'address', 'phone')

        widgets = {el: forms.TextInput(attrs={'class': 'form-control'}) for el in fields}

patient/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from datetime import date

from patient_visit.forms import PatientVisitForm
from patient_visit.models import PatientVisit
from patient_visit.views import PatientVisitCreateView
from .forms import PatientForm
from .helpers import calc_age
from .models import Patient


class PatientListView(LoginRequiredMixin, ListView):
    queryset = Patient.objects.all()
    context_object_name = 'patients'
    template_name = 'patient/patients_list.html'

    def post(self, request, *args, **kwargs):
        return PatientVisitCreateView.as_view()(request)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['patient_visit_form'] = PatientVisitForm()
        return context


class PatientDetailView(LoginRequiredMixin, DetailView):
    model = Patient
    template_name = 'patient/patient_detail.html'
    context_object_name = 'patient'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["age"] = calc_age(self.object.birth_date, date.today())
        filter_criteria = {'patient': self.object}
        all_patient_visits = PatientVisit.objects.filter(**filter_criteria).values('pk', 'start_date', 'diagnosis')
        context["all_patient_visits"] = all_patient_visits
        context['patient_visit_form'] = PatientVisitForm()
        return context

    def post(self, request, *args, **kwargs):
        return PatientVisitCreateView.as_view()(request)


class PatientCreateView(LoginRequiredMixin, CreateView):
    model = Patient
    form_class = PatientForm
    template_name = 'patient/patient_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['patient_visit_form'] = PatientVisitForm()
        return context

    def post(self, request, *args, **kwargs):
        if 'patient_visit_submit' in request.POST:
            return PatientVisitCreateView.as_view()(request)

        if 'patient_create_submit' in request.POST:
            return super().post(request, *args, **kwargs)


class PatientUpdateView(LoginRequiredMixin, UpdateView):
    model = Patient
    form_class = PatientForm
    template_name = 'patient/patient_create.html'
    context_object_name = 'patient'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['patient_visit_form'] = PatientVisitForm()
        return context

    def post(self, request, *args, **kwargs):
        if 'patient_visit_submit' in request.POST:
            return PatientVisitCreateView.as_view()(request)

        if 'patient_create_submit' in request.POST:
            return super().post(request, *args, **kwargs)


class PatientDeleteView(LoginRequiredMixin, DeleteView):
    model = Patient
    success_url = reverse_lazy('patient:patient_list')
    context_object_name = 'patient'

patient/templates/patient/patient_create.html
{% extends 'visit/base_visit.html' %}

{% block content %}
<br>

<div class="row">
    <div class="col-1"></div>
    <div class="col-9 ">
        <div class="row">
            <div class="col-md-11">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="fieldWrapper">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                    </div>
                    <br>
                    {% endfor %}
                    <div class="row">

                        <div class="col-md-1">
                            <button type="button" class="btn btn-outline-lightpink" id="backButton">
                                anuluj
                            </button>
                        </div>
                        <div class="col-md-9"></div>
                        <div class="col-md-2">
                            <button type="submit" name="patient_create_submit" class="btn btn-outline-turquoise">
                                zapisz
                            </button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
    <div class="col-2"></div>
</div>

{% endblock content %}

patient/templates/patient/patient_detail.html
{% extends 'visit/base_visit.html' %}

{% block content %}
<br>


<!--    wyświetlanie imię nazwisko i wiem-->
<div class="row">
    <div class="col-1"></div>
    <div class="col-9 ">
        <div class="row">
            <div class="col-md-11">
                <h3>{{patient.get_full_name}} </h3>
                <div class="row">
                    <div class="col-md-6">ur. {{patient.birth_date}} roku</div>
                    <div class="col-md-6">Wiek: {% for label, val in age.items %}
                        {{val}} {{label}}
                        {% empty %}
                        {% endfor %}
                    </div>
                </div>


            </div>
            <div class="col-md-1 "></div>
        </div>
        <br>
    </div>
    <div class="col-2"></div>
</div>


<div class="row">
    <div class="col-md-1"></div>
    <!--    wyświetla rozwijany panel -->
    <div class="col-md-10">
        <div data-bs-spy="scroll" data-bs-target="#navbar-example3" data-bs-smooth-scroll="true"
             class="scrollspy-example-2" tabindex="0">

            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingDane">
                        <button class="accordion-button  collapsed  "
                                type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseDane" aria-expanded="true"
                                aria-controls="collapseDane">
                            <h4 class="turquoise">Dane </h4>
                        </button>
                    </h2>
                    <div id="collapseDane" class="accordion-collapse collapse" aria-labelledby="headingDane"
                         data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <div>
                                <p>
                                <table class="table table-striped table-hover">
                                    <tbody>
                                    <td><p> PESEL </p></td>
                                    <td><p>{{patient.pesel}}</p></td>
                                    </tbody>
                                    <tbody>
                                    <td><p> Adres </p></td>
                                    <td><p>{{patient.address}}</p></td>
                                    </tbody>
                                    <tbody>
                                    <td><p> Tel. </p></td>
                                    <td><p> {% if patient.phone %}{{patient.phone}} {% else %} - {% endif %}</p></td>
                                    </tbody>
                                    <tbody>
                                    <td><p> email </p></td>
                                    <td><p>{% if patient.email %}{{patient.email}} {% else %} - {% endif %}</p></td>
                                    </tbody>
                                    <td><p> Utworzono: {{patient.created_at}}</p></td>
                                    <td><p>Zmodyfikowano: {{patient.updated_at}}</p></td>
                                    </tbody>
                                    <tbody>
                                </table>
                                </p>
                                <div class="row">
                                    <div class="col-lg-2">
                                        <button type="button" class="btn btn-outline-lightpink btn-sm"
                                                data-bs-toggle="modal"
                                                data-bs-target="#exampleModal">
                                            usuń&nbsp;pacjenta
                                        </button>
                                    </div>
                                    <div class="col-lg-8"></div>
                                    <div class="col-lg-2"><a href="{% url 'patient:patient_update' patient.pk %}">
                                        <button type="button" class="btn btn-outline-lightturquoise btn-sm"> edytuj
                                        </button>
                                    </a></div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingWizyty">
                        <button class="accordion-button "
                                type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseWizyty" aria-expanded="true"
                                aria-controls="collapseWizyty">
                            <h4 class="turquoise">Wizyty </h4>
                        </button>
                    </h2>
                    <div id="collapseWizyty" class="accordion-collapse collapse show "
                         aria-labelledby="headingWizyty"
                         data-bs-parent="#accordionExample">
                        {% include 'patient_visit/visits_accordion.html' %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{patient.get_full_name}}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Czy jesteś pewien, że chcesz usunąć tego pacjenta i wszystkie jego wizyty?
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-outline-lightturquoise" data-bs-dismiss="modal">anuluj</button>
                <form method="post" action="{% url 'patient:patient_delete' patient.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">usuń</button>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

patient/templates/patient/patient_list.html
{% extends 'visit/base_visit.html' %}
{% block content %}
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <br>
        <div class="row">
            <div class="col-md-7"><h4>Pacjenci </h4></div>
            <div class="col-md-5"><a href="{% url 'patient:patient_create' %}">
                <button type="button" class="btn btn-outline-lightturquoise">+</button>
            </a></div>

        </div>

        <br>
        <table class="table  table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Imię i nazwisko</th>
                <th scope="col">Data urodzenia</th>
            </tr>
            </thead>

            {% for patient in patients %}
            <tbody>
            <tr>
                <th scope="row">{{patient.id}}</th>
                <td><a class="turquoise" href="{{patient.get_absolute_url}}"> {{patient.get_full_name}}</a></td>

                <td><a class="turquoise" href="{{patient.get_absolute_url}}"> {{patient.birth_date}} </a></td>
            </tr>
            </tbody>

            {% empty %}
            {% endfor %}


        </table>
    </div>
    <div class="col-md-1"></div>
</div>
{% endblock content %}