config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from django.contrib.auth import views as auth_views

admin.site.site_header = "EASY Doctor Admin"
admin.site.site_title = "EASY Doctor Admin Portal"
admin.site.index_title = "Welcome to EASY Doctor Researcher Portal"

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('home/', include('home.urls', namespace='home')),
                  path('visit/', include('visit.urls', namespace='visit')),
                  path('patient/', include('patient.urls', namespace='patient')),
                  path('patient_visit/', include('patient_visit.urls', namespace='patient_visit')),
                  path("__debug__/", include("debug_toolbar.urls")),
                  # path('login/', auth_views.LoginView.as_view(), name='login'),
                  # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
                  path("accounts/", include("django.contrib.auth.urls")),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),

]

patient/urls.py
from django.urls import path

from . import views

app_name = 'patient'
urlpatterns = [
    path('', views.PatientListView.as_view(), name='patient_list'),
    path('<int:pk>/', views.PatientDetailView.as_view(), name='patient_detail'),
    path('patient_create/', views.PatientCreateView.as_view(), name='patient_create'),
    path('<int:pk>/patient_update/', views.PatientUpdateView.as_view(), name='patient_update'),
    path('<int:pk>/patient_delete/', views.PatientDeleteView.as_view(), name='patient_delete'),

]

patient_visit/urls.py
from django.urls import path

from . import views

app_name = 'patient_visit'
urlpatterns = [
    path('', views.PatientVisitListView.as_view(), name='patientvisit_list'),
    path('<int:pk>/', views.PatientVisitDetailView.as_view(), name='patientvisit_detail'),
    path('<int:pk>/update/', views.PatientVisitUpdateView.as_view(), name='patientvisit_update'),
    path('<int:pk>/delete/', views.PatientVisitDeleteView.as_view(), name='patientvisit_delete'),
    path('<int:pk>/pdf/', views.export_visit_to_pdf, name='patientvisit_pdf'),
]

patient_visit/models.py
from datetime import datetime

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from patient.models import Patient
from visit.models import TimeStampedModel

user = get_user_model()


class PatientVisit(TimeStampedModel):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_visits', verbose_name='pacjent',
                               help_text='pacjent')
    doctor = models.ForeignKey(user, on_delete=models.CASCADE, related_name='patient_visits', verbose_name='lekarz',
                               help_text='lekarz', default=2)
    diagnosis = models.TextField(verbose_name='Rozpoznanie', null=True, blank=True)
    interview = models.TextField(verbose_name='Wywiad', null=True, blank=True)
    examination = models.TextField(verbose_name='Badanie', null=True, blank=True)
    recommendations = models.TextField(verbose_name='Zalecenia', null=True, blank=True)
    start_date = models.DateTimeField(verbose_name='Rozpoczęcie wizyty', null=True, blank=True)
    end_date = models.DateTimeField(verbose_name='Zakończenie wizyty', null=True, blank=True)
    is_deleted = models.BooleanField(default=False, verbose_name='Wizytz usunięta')

    def __str__(self):
        return self.patient.get_full_name()

    class Meta:
        verbose_name = 'wizyta'
        verbose_name_plural = 'wizyty'

    def get_absolute_url(self):
        return reverse('patient_visit:patientvisit_detail', kwargs={'pk': self.pk})

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):

        print(10*"*", type(self), "self", self)
        self.start_date = datetime.now()
        super(PatientVisit, self).save()

patient_visit/forms.py
from django import forms

from patient.models import Patient
from .models import PatientVisit

patients_choices = Patient.objects.filter(doctor_id=2)


class PatientVisitForm(forms.ModelForm):
    class Meta:
        model = PatientVisit
        fields = ('patient', 'diagnosis', 'interview', 'examination', 'recommendations')

        widgets = {
            'patient': forms.Select(
                attrs={'choices': 'patients_choices', 'class': "form-select", 'aria-label': "Default select example"}),
            'diagnosis': forms.Textarea(
                attrs={'class': 'my-form-control', 'id': "diagn", 'type': "text", 'rows': '2', 'cols': '55'}),
            'interview': forms.Textarea(
                attrs={'class': 'my-form-control', 'id': "wywiad", 'type': "text", 'rows': '10', 'cols': '55'}),
            'examination': forms.Textarea(
                attrs={'class': 'my-form-control', 'id': "badanie", 'type': "text", 'rows': '10', 'cols': '55'}),
            'recommendations': forms.Textarea(
                attrs={'class': 'my-form-control', 'id': "zalecenia", 'type': "text", 'rows': '10', 'cols': '55'}),
        }


class PatientVisitUpdateForm(forms.ModelForm):
    class Meta:
        model = PatientVisit
        fields = ( 'diagnosis', 'interview', 'examination', 'recommendations')

        widgets = {
            'diagnosis': forms.Textarea(
                attrs={'class': 'my-form-control',  'type': "text", 'rows': '2', 'cols': '55'}),
            'interview': forms.Textarea(
                attrs={'class': 'my-form-control', 'type': "text", 'rows': '10', 'cols': '55'}),
            'examination': forms.Textarea(
                attrs={'class': 'my-form-control', 'type': "text", 'rows': '10', 'cols': '55'}),
            'recommendations': forms.Textarea(
                attrs={'class': 'my-form-control', 'type': "text", 'rows': '10', 'cols': '55'}),
        }

patient_visit/views.py
import io
import os
import datetime

from django.http import HttpResponse, HttpResponseForbidden
from django.contrib.auth.mixins import LoginRequiredMixin

from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, Spacer
from reportlab.platypus import SimpleDocTemplate

from config.settings import BASE_DIR

from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from patient.helpers import calc_age
from .forms import PatientVisitForm, PatientVisitUpdateForm
from .models import PatientVisit


class PatientVisitCreateView(LoginRequiredMixin, CreateView):
	template_name = 'visit/base_visit.html'
	form_class = PatientVisitForm
	model = PatientVisit


class PatientVisitListView(LoginRequiredMixin, ListView):
	queryset = PatientVisit.objects.all()
	context_object_name = 'patient_visits'
	template_name = 'patient_visit/patient_visit_list.html'
	
	# paginate_by = 10
	
	def post(self, request, *args, **kwargs):
		return PatientVisitCreateView.as_view()(request)
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['patient_visit_form'] = PatientVisitForm()
		return context


class PatientVisitDetailView(LoginRequiredMixin, DetailView):
	model = PatientVisit
	template_name = 'patient_visit/patientvisit_detail.html'
	context_object_name = 'visit'
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["age_now"] = calc_age(self.object.patient.birth_date, datetime.date.today())
		context["age_visit"] = calc_age(self.object.patient.birth_date, self.object.start_date.date())
		patient = self.object.patient
		filter_criteria = {'patient': patient}
		all_patient_visits = PatientVisit.objects.filter(**filter_criteria).values('pk', 'start_date', 'diagnosis')
		context["all_patient_visits"] = all_patient_visits
		context['patient'] = patient
		context['patient_visit_form'] = PatientVisitForm()
		return context
	
	def post(self, request, *args, **kwargs):
		return PatientVisitCreateView.as_view()(request)


class PatientVisitUpdateView(LoginRequiredMixin, UpdateView):
	model = PatientVisit
	template_name = 'patient_visit/patientvisit_update.html'
	context_object_name = 'visit'
	form_class = PatientVisitUpdateForm
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["age_now"] = calc_age(self.object.patient.birth_date, datetime.date.today())
		context["age_visit"] = calc_age(self.object.patient.birth_date, self.object.start_date.date())
		filter_criteria = {'patient': self.object.patient}
		all_patient_visits = PatientVisit.objects.filter(**filter_criteria).values('pk', 'start_date', 'diagnosis')
		context["all_patient_visits"] = all_patient_visits
		context['patient_visit_form'] = PatientVisitForm()
		return context
	
	def post(self, request, *args, **kwargs):
		
		if 'patient_visit_submit' in request.POST:
			return PatientVisitCreateView.as_view()(request)
		
		if 'patient_visit_update_submit' in request.POST:
			return super().post(request, *args, **kwargs)


class PatientVisitDeleteView(LoginRequiredMixin, DeleteView):
	model = PatientVisit
	context_object_name = 'patient_visit'
	
	def get_success_url(self):
		patient = PatientVisit.objects.get(pk=self.kwargs['pk']).patient.pk
		success_url = reverse_lazy('patient:patient_detail', args=[patient])
		return success_url.format(**self.object.__dict__)


def export_visit_to_pdf(request, pk):
	visit = PatientVisit.objects.filter(pk=pk).prefetch_related('patient')
	if len(visit) < 1:
		return HttpResponseForbidden()
	visit_values = visit.values()[0]
	visit_date = visit_values['start_date'].strftime("%d.%m.%Y  %H:%M")
	patient_name = visit[0].patient.get_full_name()
	
	# zarejestrowanie styli używanych w pdf
	pdfmetrics.registerFont(
		TTFont('Roboto-Thin', os.path.join(BASE_DIR, 'styles', 'fonts', 'RobotoCondensed-Regular.ttf')))
	pdfmetrics.registerFont(
		TTFont('Roboto-Bold', os.path.join(BASE_DIR, 'styles', 'fonts', 'RobotoCondensed-Bold.ttf')))
	sample_style_sheet = getSampleStyleSheet()
	headline1_style = sample_style_sheet["Heading1"]
	headline1_style.fontName = 'Roboto-Bold'
	title_style = sample_style_sheet["Title"]
	title_style.fontName = 'Roboto-Thin'
	body_text_style = sample_style_sheet["BodyText"]
	body_text_style.fontName = 'Roboto-Thin'
	body_text_style.bulletFontName = 'Roboto-Bold'
	
	'''Tworzenie dokumentu'''
	buf = io.BytesIO()
	doc = SimpleDocTemplate(buf, pagesize=A4, allowSplitting=False, title=patient_name + ' ' + visit_date)
	
	pdf_content = []
	
	'''Dodawanie tytułu do dokumentu'''
	paragraph_1 = Paragraph(f"{patient_name} - wizyta z dnia {visit_date}", title_style)
	pdf_content.append(paragraph_1)
	pdf_content.append(Spacer(10, 10))
	
	'''Dodawanie części wizyty do dokumentu'''
	
	age_visit_calc = calc_age(visit[0].patient.birth_date, visit_values['start_date'].date())
	age_visit = ''
	for label, amount in age_visit_calc.items():
		if amount != 0:
			age_visit += str(amount) + ' ' + label + ' '
	
	basic_paragraph = Paragraph(age_visit, body_text_style, bulletText="Wiek w dniu wizyty")
	pdf_content.append(basic_paragraph)
	
	pdf_content.append(Spacer(10, 10))
	
	visit_fields_dict = {'diagnosis': 'Rozpoznanie', 'interview': 'Wywiad', 'examination': 'Badanie',
						 'recommendations': 'Zalecenia'}
	
	for field_name in visit_fields_dict.keys():
		if field_name in visit_values.keys():
			line = visit_fields_dict[field_name]
			combined_basic_text_line = '  ' + str(visit_values[field_name])
			basic_paragraph = Paragraph(combined_basic_text_line, body_text_style, bulletText=line)
			pdf_content.append(basic_paragraph)
		
		pdf_content.append(Spacer(10, 10))
	
	basic_paragraph = Paragraph(visit[0].doctor.get_full_name(), body_text_style, bulletText="Lekarz")
	pdf_content.append(basic_paragraph)
	
	basic_paragraph = Paragraph(visit_values['updated_at'].strftime("%d.%m.%Y  %H:%M"), body_text_style,
								bulletText="Ostatnia modyfikacja")
	pdf_content.append(basic_paragraph)
	
	pdf_content.append(Spacer(10, 10))
	
	'''Budowanie dokumentu z elementami stałymi na każdej stronie'''
	doc.build(pdf_content, onFirstPage=add_to_first_page, onLaterPages=add_to_later_pages)
	buf.seek(0)
	
	'''tworzenie nazwy pliku'''
	filename = f"Wizyta {patient_name} {visit_date}.pdf"
	response = HttpResponse(buf, content_type='application/pdf')
	response["Content-Disposition"] = f'inline; filename={filename}'
	
	return response

patient_visit/templates/patient_visit/patient_visit_list.html
{% extends 'visit/base_visit.html' %}
{% block content %}
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-11">
        <br>
        <h4>Wizyty</h4>
        <table class="table  table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Pacjent</th>
                <th scope="col">Data</th>
                <th scope="col">Rozpoznanie</th>
            </tr>
            </thead>

            {% for visit in patient_visits %}

            <tbody>

            <tr>
                <th scope="row">{{visit.id}}</th>
                <td> {{visit.patient}}</td>
                <td><a class="turquoise" href="{{visit.get_absolute_url}}"> {{visit.created_at}}</a></td>
                <td><a class="turquoise" href="{{visit.get_absolute_url}}"> {{visit.diagnosis}}</a></td>
            </tr>
            </tbody>


            {% empty %}
            {% endfor %}


        </table>
    </div>
</div>
{% endblock content %}

patient_visit/templates/patient_visit/patientvisit_detail.html
{% extends 'visit/base_visit.html' %}

{% block content %}
<br>


<!--    wyświetlanie imię nazwisko i wiek-->
<div class="row">
    <div class="col-1"></div>
    <div class="col-9 ">
        <div class="row">
            <div class="col-md-11">
                <a class="turquoise" href="{% url 'patient:patient_detail' visit.patient.pk %}"><h3>
                    {{visit.patient.get_full_name}} </h3></a>
                <div class="row">
                    <div class="col-md-6">ur. {{visit.patient.birth_date}} roku</div>
                    <div class="col-md-6">Wiek: {% for label, val in age_now.items %}
                        {{val}} {{label}}
                        {% empty %}
                        {% endfor %}
                    </div>
                </div>


            </div>
            <div class="col-md-1 ">
                <button type="button" class="btn btn-outline-lightpink btn-sm" data-bs-toggle="modal"
                        data-bs-target="#exampleModal">
                    usuń&nbsp;
                </button>


            </div>
        </div>
        <br>
    </div>
    <div class="col-2"></div>
</div>


<div class="row">
    <div class="col-md-1"></div>
    <!--    wyświetla rozwijany panel -->
    <div class="col-md-10">
        <div data-bs-spy="scroll" data-bs-target="#navbar-example3" data-bs-smooth-scroll="true"
             class="scrollspy-example-2" tabindex="0">

            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingWizyta">
                        <button class="accordion-button  collapsed  "
                                type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseWizyta" aria-expanded="true"
                                aria-controls="collapseWizyta">
                            <h4 class="turquoise">Wizyta z dnia {{visit.start_date}} </h4>
                        </button>
                    </h2>
                    <div id="collapseWizyta" class="accordion-collapse collapse show" aria-labelledby="headingWizyta"
                         data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <div>
                                <p>
                                <table class="table table-striped table-hover">
                                    <tbody>
                                    <td><p>Wiek </p></td>
                                    <td><p> {% for label, val in age_visit.items %}
                                        {{val}} {{label}}
                                        {% empty %}
                                        {% endfor %}</p></td>
                                    </tbody>
                                    <tbody>
                                    <td><p> Rozpoznanie </p></td>
                                    <td><p>{{visit.diagnosis}}</p></td>
                                    </tbody>
                                    <tbody>
                                    <td><p> Wywiad </p></td>
                                    <td><p>{{visit.interview}}</p></td>
                                    </tbody>
                                    <tbody>
                                    <td><p> Badanie </p></td>
                                    <td><p>{{visit.examination}} </p></td>
                                    </tbody>
                                    <tbody>
                                    <td><p> Zalecenia </p></td>
                                    <td><p>{{visit.recommendations}} </p></td>
                                    </tbody>
                                    <td><p>Zmodyfikowano </p></td>
                                    <td><p>{{visit.updated_at}}</p></td>
                                    </tbody>
                                    <tbody>
                                </table>
                                </p>
                                <div class="row">
                                    <div class="col-lg-2">
                                        <button type="button" class="btn btn-outline-lightpink btn-sm"
                                                data-bs-toggle="modal"
                                                data-bs-target="#patientVisitDeleteModal"> usuń wizytę
                                        </button>
                                    </div>
                                    <div class="col-lg-6"></div>
                                    <div class="col-lg-2"><a target="_blank"
                                            href="{% url 'patient_visit:patientvisit_pdf' visit.pk %}">
                                        <button type="button" class="btn btn-outline-lightturquoise btn-sm"> pdf wizyta
                                        </button>
                                    </a></div>
                                    <div class="col-lg-2"><a
                                            href="{% url 'patient_visit:patientvisit_update' visit.pk %}">
                                        <button type="button" class="btn btn-outline-lightturquoise btn-sm"> edytuj
                                        </button>
                                    </a></div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingWizyty">
                        <button class="accordion-button "
                                type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseWizyty" aria-expanded="true"
                                aria-controls="collapseWizyty">
                            <h4 class="turquoise">Wszystkie wizyty </h4>
                        </button>
                    </h2>
                    <div id="collapseWizyty" class="accordion-collapse show"
                         aria-labelledby="headingWizyty"
                         data-bs-parent="#accordionExample">
                        {% include 'patient_visit/visits_accordion.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-md-1"></div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{patient.get_full_name}}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Czy jesteś pewien, że chcesz usunąć tego pacjenta i wszystkie jego wizyty?
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-outline-lightturquoise" data-bs-dismiss="modal">
                    anuluj
                </button>
                <form method="post" action="{% url 'patient:patient_delete' patient.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">usuń</button>
                </form>

            </div>
        </div>
    </div>
</div>

<!-- Modal do potwierdzenia usunięcia wizyty -->
<div class="modal fade" id="patientVisitDeleteModal" tabindex="-1" aria-labelledby="patientVisitDeleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="patientVisitDeleteModalLabel">
                    {{visit.patient.get_full_name}}
                    <br>Wizyta {{ visit.start_date }}
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Czy jesteś pewien, że chcesz usunąć wizytę?
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-outline-lightturquoise" data-bs-dismiss="modal">
                    anuluj
                </button>
                <form method="post" action="{% url 'patient_visit:patientvisit_delete' visit.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">usuń</button>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

patient_visit/templates/patient_visit/patientvisit_update.html
{% extends 'visit/base_visit.html' %}

{% block content %}
<br>

<div class="row">
    <div class="col-1"></div>
    <div class="col-9 ">
        <div class="row">
            <div class="col-md-11">
                <p>{{visit.patient}}</p>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="fieldWrapper">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                    </div>
                    <br>
                    {% endfor %}
                    <div class="row">

                        <div class="col-md-1">
                            <button type="button" class="btn btn-outline-lightpink" id="backButton">
                                anuluj
                            </button>
                        </div>

                        <div class="col-md-9"></div>

                        <div class="col-md-2">
                            <button name="patient_visit_update_submit" type="submit" class="btn btn-outline-turquoise">
                                zapisz
                            </button>
                        </div>

                    </div>
                </form>

            </div>
        </div>
    </div>
    <div class="col-2"></div>
</div>

{% endblock content %}

patient_visit/templates/patient_visit/visits_accordion.html
<div class="accordion-body">
    <div>
        <div class="row">
            <div class="col-lg-10"></div>
            <div class="col-lg-2">
                <button type="button" class="btn btn-outline-lightturquoise btn-sm" onclick="createPatientVisit('{{ patient.pk }}')"> nowa
                    wizyta
                </button>
           </div>
        </div>
        <p>
        <table class="table table-striped table-hover">
            {% for one_visit in all_patient_visits %}
            <tbody>
            <td>
                <p> {{one_visit.start_date}} </p>
            </td>
            <td>
                <a class="turquoise" href="{% url 'patient_visit:patientvisit_detail' one_visit.pk %}"><p>
                    {{one_visit.diagnosis}}
                </p></a>
            </td>
            </tbody>
            {% empty %}
            {% endfor %}


        </table>
        </p>
    </div>
</div>

<script !src="">
    // function createPatientVisit(patientPk) {
    //     clearSession()
    //     document.getElementById("id_patient").value = patientPk;
    //     document.getElementsByName("patient").forEach(saveInSessionStorage)
    // }
</script>